version: '3.6'

networks:
  traefik:
    name: traefik
    driver: bridge

services:
  traefik:
    image: traefik:1.7
    container_name: atlassian-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=false"
      - "traefik.backend=traefik"
      - "traefik.docker.network=traefik"
      - "traefik.frontend.redirect.entryPoint=https"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./atlassian-proxy/traefik.toml:/traefik.toml:ro
      - ./atlassian-proxy/acme:/etc/traefik/acme
    networks:
      - traefik

  database:
    image: atlassian-postgres
    container_name: database
    restart: always
    expose:
        - "5432"
    labels:
      - "traefik.enable=false"
    volumes:
        - database:/var/lib/postgresql
    networks:
      - traefik

  jira:
    image: atlassian-jira
    container_name: jira
    restart: always
    depends_on:
      - database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jira"
      - "traefik.frontend.rule=PathPrefix:/jira"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik"
    environment:
      - JVM_MINIMUM_MEMORY=512m
      - JVM_MAXIMUM_MEMORY=2048m
      - CATALINA_CONNECTOR_SCHEME=https
      - CATALINA_CONNECTOR_SECURE=true
      - CATALINA_CONNECTOR_PROXYNAME=${DOMAIN_NAME}
      - CATALINA_CONNECTOR_PROXYPORT=443
      - CATALINA_CONTEXT_PATH=/jira
    volumes:
        - jira:/opt/atlassian/jira-data
    networks:
      - traefik
  
volumes:
    database:
        name: database
        driver: local
    jira:
        name: jira
        driver: local
