################################################################
# Traefik configuration
################################################################

debug = false

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email = "dennis@butt3rweck.com"
  storage = "/etc/traefik/acme/acme.json"
  onDemand = true
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  entryPoint = "https"
    [acme.httpChallenge]
    entryPoint = "http"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = false

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "devops.ancud.de"
  watch = true
  exposedByDefault = false
  usebindportip = true
  swarmMode = false
  network = "traefik"
